# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 18000 #5 hrs # Corvax-RoleTime
#    - !type:RoleTimeRequirement
#      role: JobMedicalDoctor
#      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 43200 # Corvax-RoleTime
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  radioBold: true # A-13 upgraded chat system
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CMOGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedicalFilled
    underwearb: ClothingUnderwearBottomBoxersCMO # Andromeda-Underwear
  underweart: ClothingUnderwearTopBraCMO # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesCMO # Andromeda-Underwear
