- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 43200 # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 43200 # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 43200 # Corvax-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 216000 # Corvax-RoleTime
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  radioBold: true # A-13 upgraded chat system
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
    underwearb: ClothingUnderwearBottomBoxersCap # Andromeda-Underwear
  underweart: ClothingUnderwearTopBraCap # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesCap # Andromeda-Underwear
