- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Cluster
  - Bagel
#  - Barratry
#  - Train
  - CorvaxDelta
  - Marathon
  - Box
  - CorvaxAstra
#  - CorvaxAvrite
#  - CorvaxSpectrum
#  - Oasis
  - Omega
  - Packed
#  - CorvaxOutpost
  - Meta
  - Fland
  - Core
#  - Origin
  - CorvaxSilly
  - Atlas
  - Saltern
#  - Reach
