- type: department
  id: Cargo
  description: department-Cargo-description
  color: "#A46106"
  sort: 0 # A-13 upgraded chat system
  roles:
  - CargoTechnician
  - Quartermaster
  - SalvageSpecialist

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  sort: 2 # A-13 upgraded chat system
  weight: -10
  roles:
  - Bartender
  - Borg
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - HeadOfPersonnel
  - Janitor
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  sort: 1 # A-13 upgraded chat system
  roles:
  - Captain
  - IAA # Corvax-IAA
  - CentralCommandOfficial
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  primary: false
  weight: 100

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  sort: 0 # A-13 upgraded chat system
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  sort: 0 # A-13 upgraded chat system
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - MedicalIntern
  - Psychologist
  - Paramedic

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  sort: 0 # A-13 upgraded chat system
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Pilot # Corvax-Pilot
  - Detective
  - Warden

- type: department
  id: Science
  description: department-Science-description
  color: "#D381C9"
  sort: 0 # A-13 upgraded chat system
  roles:
  - ResearchDirector
  - Scientist
  - ResearchAssistant

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  sort: 0 # A-13 upgraded chat system
  weight: 10
  roles:
  - Boxer
  - Reporter
  - Zookeeper
  #- Psychologist # A-13 upgraded chat system
  primary: false

# A-13 Ghost roles bans
- type: department
  id: GhostRoles
  sort: 0
  description: Ghost roles
  color: "#A9A9A9"
  roles:
  - GhostRole
