- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  requirements:
#    - !type:RoleTimeRequirement
#      role: JobCargoTechnician
#      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 36000 #10 hrs # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 43200 # Corvax-RoleTime
#    - !type:OverallPlaytimeRequirement
#      time: 108000
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-captain
  canBeAntag: false
  radioBold: true # A-13 upgraded chat system
  access:
  - Cargo
  - Salvage
  - Quartermaster
  - Maintenance
  - Command
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
    underwearb: ClothingUnderwearBottomBoxersQM # Andromeda-Underwear
  underweart: ClothingUnderwearTopBraQM # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesQM # Andromeda-Underwear
