- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 43200 # Corvax-RoleTime
#    - !type:OverallPlaytimeRequirement
#      time: 108000
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  radioBold: true # A-13 upgraded chat system
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Brig
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetRD
    underwearb: ClothingUnderwearBottomBoxersRD # Andromeda-Underwear
  underweart: ClothingUnderwearTopBraRD # Andromeda-Underwear
  underwearb: ClothingUnderwearBottomPantiesRD # Andromeda-Underwear
